### ISSUE TITLE
Warnings when used with gather_subset

### ISSUE THREAD

**Issue by mtdcr** [samdoran/ansible-collection-armbian#1]
Running a playbook with gather_subset generates warnings with ansible 2.10.6.

```yaml
- hosts: all
  gather_facts: True
  gather_subset: min
```
```
[WARNING]: Ignoring subset(['min']) for samdoran.armbian.armbian_facts
[WARNING]: Ignoring timeout(10) for samdoran.armbian.armbian_facts
```
I configured your module like this in ansible.cfg:
```ini
facts_modules = samdoran.armbian.armbian_facts
```
